
# Root of data directory
data_dir = "DataProjects/phospholamban-cardiomyocytes/RNA-seq/ribo-zero"

# Load gene expression count matrices generated by tuxedo2 
# .cvs files collated by prepDE.py
count_mat = fread(file.path(data_dir, "merged/gene_count_matrix.csv"))
count_mat = rename(count_mat, c("V1"="gene_id"))  # rename for convenience


# Load sample info
pheno = 